// SPDX-License-Identifier: AGPL-3.0-only
// Generated fixtures; real UI controls, geometry worker and effects.
import { launchApp, check, fail, finish } from './e2e-lib.mjs'

const { browser, page, consoleErrors } = await launchApp({ protocolTimeout: 180_000 })
page.on('dialog', (dialog) => dialog.accept())
try {
  const checks = await page.evaluate(async () => {
    const { useStore: measure } = await import('/src/state/store.ts')
    const { useFlat: flat } = await import('/src/state/flatStore.ts')
    const { useDeviation: deviation } = await import('/src/state/deviationStore.ts')
    const { useThickness: thickness } = await import('/src/state/thicknessStore.ts')
    const { useShell: shell } = await import('/src/state/shellStore.ts')
    const history = await import('/src/state/historyStore.ts')
    const { SceneManager } = await import('/src/viewer/SceneManager.ts')
    const { MeshWorkerClient } = await import('/src/core/workerClient.ts')
    const results = []
    const record = (ok, name) => results.push({ ok: !!ok, name })
    const pause = (ms = 40) => new Promise((resolve) => setTimeout(resolve, ms))
    const wait = async (predicate, name) => {
      for (let i = 0; i < 1500; i++) { await pause(); if (predicate()) return }
      throw new Error(`${name}: ${measure.getState().errorText ?? measure.getState().statusText}; ${JSON.stringify(results)}`)
    }
    const drop = (file) => {
      const dataTransfer = new DataTransfer(); dataTransfer.items.add(file)
      window.dispatchEvent(new DragEvent('drop', { dataTransfer, bubbles: true, cancelable: true }))
    }
    const click = (test) => {
      const button = document.querySelector(`[data-test="${test}"]`)
      if (!button || button.disabled) throw new Error(`Unavailable button: ${test}`)
      button.click()
    }
    const travel = async (redo = false, shortcut = false) => {
      const revision = history.useHistory.getState().revision
      if (shortcut) window.dispatchEvent(new KeyboardEvent('keydown', { key: 'z', ctrlKey: true, shiftKey: redo, bubbles: true, cancelable: true }))
      else click(redo ? 'redo' : 'sketch-undo')
      await wait(() => history.useHistory.getState().revision > revision && !history.useHistory.getState().restoring, 'history settled')
      await pause(100)
    }
    let scene
    const prepare = SceneManager.prototype.prepareMesh
    SceneManager.prototype.prepareMesh = function (...args) { scene = this; return prepare.apply(this, args) }
    const cube = 'v 0 0 0\nv 10 0 0\nv 10 10 0\nv 0 10 0\nv 0 0 10\nv 10 0 10\nv 10 10 10\nv 0 10 10\nf 1 3 2\nf 1 4 3\nf 5 6 7\nf 5 7 8\nf 1 2 6\nf 1 6 5\nf 2 3 7\nf 2 7 6\nf 3 4 8\nf 3 8 7\nf 4 1 5\nf 4 5 8\n'
    try {
      drop(new File([cube], 'history-cube.obj'))
      await wait(() => measure.getState().fileName === 'history-cube.obj' && !measure.getState().busy, 'scan imported')
    } finally { SceneManager.prototype.prepareMesh = prepare }
    const m = () => measure.getState(), f = () => flat.getState(), d = () => deviation.getState(), t = () => thickness.getState()
    const point = { id: 1, kind: 'point', name: 'Point 1', color: '#ff8800', source: { type: 'picked' }, status: 'done', visible: true,
      fit: { kind: 'point', center: [0, 0, 0], sigma: 0, usedPoints: 0, regionSize: 0 } }
    measure.setState({ elements: [point], nextId: 2 })
    m().removeElement(1)
    await pause()
    await travel()
    record(m().elements[0]?.id === 1, 'Measure undo restores a deleted element through the toolbar')
    await travel(true, true)
    record(m().elements.length === 0, 'Ctrl+Shift+Z redoes Measure deletion')

    // The fitted-element map is regenerated by a React effect, after history
    // applies its state. Verify those effects do not erase restored probes.
    measure.setState({ elements: [{ ...point, kind: 'plane', fit: { kind: 'plane', center: [0, 0, 0], normal: [0, 0, 1], basisU: [1, 0, 0], basisV: [0, 1, 0], extentU: 20, extentV: 20, sigma: 0, usedPoints: 0, regionSize: 0 } }] })
    shell.getState().setWorkspace('deviation')
    d().setSource('element'); d().setTarget(1)
    await wait(() => d().elementStatus === 'ready', 'element field ready')
    d().addProbe([1, 1, 0], 0)
    history.clearHistory()
    await pause()
    m().removeElement(1)
    await pause()
    await travel()
    record(d().targetId === 1 && d().elementStatus === 'ready' && d().probes.length === 1,
      'undo restores an element, its deviation map and pins after React effects settle')
    d().flipTargetSide()
    await pause()
    await travel()
    record(d().targetSide === 1 && d().probes.length === 1, 'undo restores map side and its original pins')
    await travel(true)
    record(d().targetSide === -1 && d().probes.length === 0, 'redo invalidates pins from the previous map side')

    const canvas = document.createElement('canvas'); canvas.width = 100; canvas.height = 100
    const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png'))
    drop(new File([blob], 'history-sheet.png'))
    await wait(() => f().imageName === 'history-sheet.png' && !m().busy, 'image imported')
    record(history.useHistory.getState().past.length === 0, 'successful image replacement starts fresh history')
    f().startCalibration('distance'); f().addCalPick([0, 0]); f().addCalPick([100, 0]); f().applyCalibration(10)
    f().startDraft('point', 'flat-point-pick'); f().addDraftPick([50, 50]); f().commitDraft()
    const calibrated = f().pxPerMm
    f().startCalibration('distance'); f().addCalPick([0, 0]); f().addCalPick([100, 0]); f().applyCalibration(20)
    await pause()
    await travel()
    record(f().pxPerMm.x === calibrated.x && f().elements[0].fit.at[0] === 5,
      '2D calibration undo restores scale and measurement coordinates')
    await travel(true)
    record(f().elements[0].fit.at[0] === 10, '2D calibration redo updates measured coordinates')

    shell.getState().setWorkspace('thickness')
    const limit = t().limit
    t().setLimit(2.5)
    shell.getState().setWorkspace('flat')
    await pause()
    await travel(false, true)
    record(shell.getState().workspace === 'thickness' && t().limit === limit,
      'Ctrl+Z follows chronological history back to the originating workspace')
    await travel(true)
    t().addProbe([0, 0, 0], 10)
    await pause()
    await travel()
    record(t().probes.length === 0, 'Thickness probe undo removes the pin')
    await travel(true)
    record(t().probes[0]?.value === 10, 'Thickness probe redo restores the reading')
    click('measure-thickness')
    await wait(() => t().status === 'ready', 'thickness field measured')
    t().addProbe([0, 0, 0], 10)
    const mapVersion = t().mapVersion
    t().setConeRays(6)
    await pause()
    await travel()
    record(t().coneRays === 0 && t().status === 'ready' && t().mapVersion > mapVersion && t().probes.length === 1,
      'undoing thickness search settings recomputes the field and preserves restored pins')

    // Input fields retain the browser's own text undo.
    const input = document.createElement('input'); document.body.append(input); input.focus()
    const count = history.useHistory.getState().past.length
    const event = new KeyboardEvent('keydown', { key: 'z', ctrlKey: true, bubbles: true, cancelable: true })
    input.dispatchEvent(event)
    await pause()
    record(!event.defaultPrevented && history.useHistory.getState().past.length === count, 'text input undo is not intercepted')
    input.remove()

    // Run a real rigid transform through App's manual alignment UI.
    shell.getState().setWorkspace('elements')
    history.clearHistory()
    await pause(100)
    const x = scene.scanGeometry().getAttribute('position').getX(0)
    let workerTransforms = 0
    const transform = MeshWorkerClient.prototype.transform
    MeshWorkerClient.prototype.transform = async function (...args) { workerTransforms++; return transform.apply(this, args) }
    click('start-manual')
    await pause()
    const field = document.querySelector('[data-test="manual-mx"]')
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(field, '5')
    field.dispatchEvent(new Event('input', { bubbles: true }))
    await pause()
    click('apply-manual')
    await wait(() => !m().busy && m().appliedAlignment !== null, 'manual alignment applied')
    await pause()
    record(Math.abs(scene.scanGeometry().getAttribute('position').getX(0) - x - 5) < 1e-5,
      'manual alignment moves the actual scan geometry')
    record(t().probes[0]?.point[0] === 5, 'thickness pins move with the aligned scan')
    await travel()
    record(m().appliedAlignment === null && Math.abs(scene.scanGeometry().getAttribute('position').getX(0) - x) < 1e-5,
      'alignment undo restores scan coordinates and the alignment record')
    record(t().probes[0]?.point[0] === 0, 'alignment undo restores thickness pins in the original coordinates')
    await travel(true)
    record(workerTransforms === 3 && Math.abs(scene.scanGeometry().getAttribute('position').getX(0) - x - 5) < 1e-5,
      'alignment redo transforms both the scene and geometry worker')
    MeshWorkerClient.prototype.transform = transform

    // Saving leaves session history usable; dirty tracking follows the state
    // reached by undo/redo, and reopening the saved archive starts fresh.
    let saved
    const createURL = URL.createObjectURL, anchorClick = HTMLAnchorElement.prototype.click
    URL.createObjectURL = (blob) => { saved = blob; return createURL(blob) }
    HTMLAnchorElement.prototype.click = function () { if (!this.download) anchorClick.call(this) }
    const dirty = () => {
      const event = new Event('beforeunload', { cancelable: true }); window.dispatchEvent(event)
      return event.defaultPrevented
    }
    try {
      const count = history.useHistory.getState().past.length
      click('save-project')
      await wait(() => saved && !m().busy, 'project saved')
      record(!dirty() && history.useHistory.getState().past.length === count, 'saving keeps session undo history and marks the project saved')
      await travel()
      record(dirty(), 'undo after saving marks the project dirty')
      await travel(true)
      record(!dirty(), 'redo back to the saved document clears its dirty flag')
    } finally { URL.createObjectURL = createURL; HTMLAnchorElement.prototype.click = anchorClick }

    const beforeFailedImport = history.useHistory.getState().past.length
    drop(new File(['not geometry'], 'broken.obj'))
    await wait(() => !m().busy && !!m().errorText, 'failed import finished')
    record(history.useHistory.getState().past.length === beforeFailedImport, 'failed imports preserve undo history')
    drop(new File([saved], 'history.scanruler'))
    await wait(() => !m().busy && m().statusText.includes('Project opened'), 'saved project reopened')
    record(history.useHistory.getState().past.length === 0 && history.useHistory.getState().future.length === 0,
      'reopening a project starts fresh history')
    drop(new File([cube], 'replacement.obj'))
    await wait(() => !m().busy && m().fileName === 'replacement.obj', 'replacement scan imported')
    await pause()
    record(history.useHistory.getState().past.length === 0 && history.useHistory.getState().future.length === 0,
      'successful scan replacement clears undo and redo across all workspaces')
    return results
  })
  for (const { ok, name } of checks) check(ok, name)
} catch (error) { fail(error.stack ?? error.message) }
await finish(browser, consoleErrors)
